version: '3.8'

services:
  web:
    image: your-dotnet-image:latest
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Testoo"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"  # Expose SQL Server port
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data: